# Generated by Django 5.1.5 on 2025-02-07 03:10

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_projectpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='module',
            field=models.CharField(choices=[('Introducción', 'Introduccion'), ('Instalación', 'Instalacion'), ('Inicio Rápido', 'Incion Rapido'), ('Funcionalidades Principales', 'Funcionalidades Principales'), ('Configuración Avanzada', 'Configuración Avanzada'), ('Solución de Problemas', 'Solución De Problemas'), ('Soporte y Contacto', 'Soporte Y Contacto'), ('Apendice', 'Apendice')], default='Introducción', max_length=50, verbose_name='modulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='contenido'),
        ),
    ]
