# Generated by Django 5.1.5 on 2025-02-07 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_module_alter_post_content'),
        ('project', '0003_project_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='module',
            field=models.CharField(choices=[('Introducción', 'Introducción'), ('Instalación', 'Instalación'), ('Inicio Rápido', 'Inicion Rápido'), ('Funcionalidades Principales', 'Funcionalidades Principales'), ('Configuración Avanzada', 'Configuración Avanzada'), ('Solución de Problemas', 'Solución De Problemas'), ('Soporte y Contacto', 'Soporte Y Contacto'), ('Apendice', 'Apendice')], max_length=50, verbose_name='modulo'),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='project.project'),
        ),
    ]
