# Generated by Django 5.1.5 on 2025-02-07 23:52

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_module_alter_projectpost_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpost',
            name='post',
        ),
        migrations.AddField(
            model_name='projectpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='example software description.', verbose_name='Contenido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpost',
            name='module',
            field=models.CharField(default='Introducción', max_length=50, verbose_name='modulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpost',
            name='title',
            field=models.CharField(default='test', max_length=50, verbose_name='titulo'),
            preserve_default=False,
        ),
    ]
