# Generated by Django 5.1.5 on 2025-02-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_projectpost_post_projectpost_content_and_more'),
        ('project', '0004_categorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
