# Generated by Django 5.1.5 on 2025-03-29 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('project', '0013_remove_project_version_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='project.project'),
            preserve_default=False,
        ),
    ]
