# Generated by Django 5.1.5 on 2025-03-29 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_participant_project'),
        ('project', '0013_remove_project_version_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='project.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
