# Generated by Django 5.1.5 on 2025-04-08 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_organization_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='author.organization'),
        ),
    ]
