# Generated by Django 5.1.5 on 2025-04-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_alter_participant_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Director de proyecto', 'Director De Proyecto'), ('Desarrollador', 'Desarrollador'), ('Investigador', 'Investigador'), ('Cliente', 'Cliente'), ('Usuario', 'Usuario')], max_length=150)),
                ('participant', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.RemoveField(
            model_name='participant',
            name='rol',
        ),
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.ManyToManyField(related_name='roles', to='author.role'),
        ),
    ]
