# Generated by Django 5.1.5 on 2025-04-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_role_remove_participant_rol_participant_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('Director de proyecto', 'Director De Proyecto'), ('Desarrollador', 'Desarrollador'), ('Investigador', 'Investigador'), ('Desarrollador e Investigador', 'Desarrollador E Investigador'), ('Cliente', 'Cliente'), ('Usuario', 'Usuario')], default='Desarrollador', max_length=150),
            preserve_default=False,
        ),
    ]
