# Generated by Django 5.1.5 on 2025-04-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_remove_participant_role_delete_role_participant_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('Director de proyecto', 'Director De Proyecto'), ('Desarrollador', 'Desarrollador'), ('Investigador', 'Investigador'), ('Desarrollador e Investigador', 'Desarrollador E Investigador'), ('Cliente', 'Cliente'), ('Usuario', 'Usuario')], default='Desarrollador', max_length=150),
        ),
    ]
