# Generated by Django 5.1.5 on 2025-02-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='version'),
        ),
    ]
