# Generated by Django 5.1.5 on 2025-02-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(choices=[('Propietario', 'Propietario'), ('Libre', 'Libre'), ('Codigo Abierto', 'Codigo Abierto')], default='Propietario', max_length=50, verbose_name='Tipo de licencia')),
                ('software', models.CharField(choices=[('Anthivirus', 'Anthivirus'), ('Business Intelligence BI', 'Business Intelligence Bi'), ('Cuidado De Mascotas', 'Cuidado De Mascotas'), ('Calculo Y Analisis De Datos', 'Calculo Y Analisis De Datos'), ('Correo Electronico', 'Correo Electronico'), ('Creacion De Contenido Multimedia', 'Creacion De Contenido Multimedia'), ('Creacion De Documentos', 'Creacion De Documentos'), ('Calendarios', 'Calendarios'), ('Compresor De Archivos', 'Compresor De Archivos'), ('Cursos En Linea', 'Cursos En Linea'), ('Contabilidad Y Finanzas', 'Contabilidad Y Finanzas'), ('Desarrollo De Software', 'Desarrollo De Software'), ('Diseño Grafico', 'Diseño Grafico'), ('Diseño Y Modelado', 'Diseño Y Modelado'), ('Educacion Y Aprendizaje', 'Educacion Y Aprendizaje'), ('Editores De Imagenes', 'Editores De Imagenes'), ('E commerce', 'E Commerce'), ('Editores De Video', 'Editores De Video'), ('Gestion Bases De Datos', 'Gestion Bases Datos'), ('Gestion De Archivos y carpetas', 'Gestion De Archivos Y Carpetas'), ('Gestion De Dispositivos', 'Gestion De Dispositivos'), ('Gestion De Tareas', 'Gestion De Tareas'), ('Hojas De Calculo', 'Hojas De Calculo'), ('Gestion De Relaciones Con Clientes CRM', 'Gestion De Relaciones Con Clientes Crm'), ('Gestion Del Tiempo', 'Gestion Del Tiempo'), ('Gestion De Proyectos', 'Gestion De Proyectos'), ('Herramientas Educativas', 'Herramientas Educativas'), ('Herramientas De Mineria De Datos', 'Herramientas De Mineria De Datos'), ('Herramientas De Inteligencia Artificial', 'Herramientas De Inteligencia Artificial'), ('Juegos', 'Juegos'), ('Libros Electronicos', 'Libros Electronicos'), ('Mensajeria Instantanea', 'Mesangeria Instantanea'), ('Notas', 'Notas'), ('Navegadores Web', 'Navegadores Web'), ('Presentaciones', 'Presentaciones'), ('Procesamiento De Textos', 'Procesamiento De Textos'), ('Redes Sociales', 'Redes Sociales'), ('Reproducción Multimedia De Audio Y Video', 'Reproduccion Multimedia De Audio Y Video'), ('Software_De_Musica', 'Software De Musica'), ('Servicios De Transmision', 'Servicios De Transmision'), ('Software De Idiomas', 'Software De Idiomas'), ('Salud Y Cuidado Personal', 'Salud Y Cuidado Personal'), ('Seguridad Informatica', 'Seguridad Informatica'), ('Traduccion De Idiomas', 'Traduccion De Idiomas'), ('Videollamadas', 'Videollamadas')], max_length=150, verbose_name='Tipo de software')),
                ('category', models.TextField(choices=[('Software de productividad ayuda a los usuarios a realizar tareas comunes de manera más eficiente.', 'Productividad'), ('Software de creatividad ayuda a los usuarios a crear contenido multimedia, como imágenes, videos y música.', 'Creatividad'), ('El software de comunicación ayuda a los usuarios a comunicarse con otros.', 'Comunicacion'), ('El software empresarial ayuda a las empresas a realizar sus operaciones.', 'Negocios'), ('El software de programación ayuda a los desarrolladores a crear distintas aplicaciones.', 'Programacion'), ('El software de entretenimiento ayuda a los usuarios a relajarse y divertirse.', 'Entretenimiento'), ('El software educativo ayuda a los usuarios a aprender cosas nuevas.', 'Educacion'), ('El software de bienestar se enfoca en el cuidado de la salud de los usuarios.', 'Bienestar Y Salud')], default='Software de productividad ayuda a los usuarios a realizar tareas comunes de manera más eficiente.', max_length=255, verbose_name='Categoría')),
                ('sector', models.CharField(choices=[('Salud', 'Salud'), ('Educación', 'Educacion'), ('Finanzas y economia', 'Finanzas Y Economia'), ('Manufactura', 'Manufactura'), ('Transporte y logistica', 'Transporte Y Logistica'), ('Agricultura', 'Agricultura'), ('Gobierno', 'Gobierno'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Energía', 'Energia'), ('Recursos Humanos', 'Recursos Humanos'), ('Marketing', 'Marketing'), ('Legal', 'Legal'), ('Construcción', 'Construccion'), ('Turismo', 'Turismo'), ('Bienes Raíces', 'Bienes Raices'), ('Entretenimiento', 'Entretenimiento'), ('Deportes', 'Deportes'), ('Ciencia e investigación', 'Ciencia E Investigacion'), ('Servicios Publicos', 'Servicios Publicos'), ('Desarrollo de Software', 'Software')], max_length=200, verbose_name='sector')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'verbose_name': 'Categorization',
                'verbose_name_plural': 'Categorizations',
            },
        ),
    ]
