# Generated by Django 5.1.5 on 2025-02-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_categorization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='function_main',
            field=models.CharField(default='gestion', max_length=255, verbose_name='Función principal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='goal_main',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Objectivo principal'),
        ),
        migrations.AddField(
            model_name='project',
            name='public_goal',
            field=models.CharField(default='estudiantes', max_length=150, verbose_name='Público objectivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre del software'),
        ),
    ]
