# Generated by Django 5.1.5 on 2025-02-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='goal_main',
            field=models.CharField(max_length=255, verbose_name='Objectivo principal'),
        ),
    ]
