# Generated by Django 5.1.5 on 2025-02-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_goal_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorization',
            name='category',
            field=models.TextField(choices=[('Productividad', 'Productividad'), ('Creatividad', 'Creatividad'), ('Comunicación', 'Comunicacion'), ('Negocios', 'Negocios'), ('Programación', 'Programacion'), ('Entretenimiento', 'Entretenimiento'), ('Educativo', 'Educacion'), ('Bienestar y Salud', 'Bienestar Y Salud')], default='Productividad', max_length=255, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='sector',
            field=models.CharField(choices=[('Estilo de Vida', 'Estilo De Vida'), ('Salud', 'Salud'), ('Educación', 'Educacion'), ('Finanzas y economia', 'Finanzas Y Economia'), ('Manufactura', 'Manufactura'), ('Transporte y logistica', 'Transporte Y Logistica'), ('Agricultura', 'Agricultura'), ('Gobierno', 'Gobierno'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Energía', 'Energia'), ('Recursos Humanos', 'Recursos Humanos'), ('Marketing', 'Marketing'), ('Legal', 'Legal'), ('Construcción', 'Construccion'), ('Turismo', 'Turismo'), ('Bienes Raíces', 'Bienes Raices'), ('Entretenimiento', 'Entretenimiento'), ('Deportes', 'Deportes'), ('Ciencia e investigación', 'Ciencia E Investigacion'), ('Servicios Publicos', 'Servicios Publicos'), ('Desarrollo de Software', 'Software'), ('Cuidado Animal', 'Cuidado Animal')], max_length=200, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='software',
            field=models.CharField(choices=[('Anthivirus', 'Anthivirus'), ('Business Intelligence BI', 'Business Intelligence Bi'), ('Calculo Y Analisis De Datos', 'Calculo Y Analisis De Datos'), ('Correo Electronico', 'Correo Electronico'), ('Creacion De Contenido Multimedia', 'Creacion De Contenido Multimedia'), ('Creacion De Documentos', 'Creacion De Documentos'), ('Calendarios', 'Calendarios'), ('Compresor De Archivos', 'Compresor De Archivos'), ('Contabilidad Y Finanzas', 'Contabilidad Y Finanzas'), ('Desarrollo De Software', 'Desarrollo De Software'), ('Diseño Grafico', 'Diseño Grafico'), ('Diseño Y Modelado', 'Diseño Y Modelado'), ('Editores De Imagenes', 'Editores De Imagenes'), ('Editores De Video', 'Editores De Video'), ('Gestion Bases De Datos', 'Gestion Bases Datos'), ('Gestion De Archivos y carpetas', 'Gestion De Archivos Y Carpetas'), ('Gestion De Dispositivos', 'Gestion De Dispositivos'), ('Gestion De Tareas', 'Gestion De Tareas'), ('E commerce', 'E Commerce'), ('Educacion Y Aprendizaje', 'Educacion Y Aprendizaje'), ('Hojas De Calculo', 'Hojas De Calculo'), ('Gestion De Relaciones Con Clientes CRM', 'Gestion De Relaciones Con Clientes Crm'), ('Gestion Del Tiempo', 'Gestion Del Tiempo'), ('Gestion De Proyectos', 'Gestion De Proyectos'), ('Herramientas Educativas', 'Herramientas Educativas'), ('Herramientas De Mineria De Datos', 'Herramientas De Mineria De Datos'), ('Herramientas De Inteligencia Artificial', 'Herramientas De Inteligencia Artificial'), ('Juegos', 'Juegos'), ('Libros Electronicos', 'Libros Electronicos'), ('Mensajeria Instantanea', 'Mesangeria Instantanea'), ('Notas', 'Notas'), ('Navegadores Web', 'Navegadores Web'), ('Presentaciones', 'Presentaciones'), ('Procesamiento De Textos', 'Procesamiento De Textos'), ('Redes Sociales', 'Redes Sociales'), ('Reproducción Multimedia De Audio Y Video', 'Reproduccion Multimedia De Audio Y Video'), ('Software_De_Musica', 'Software De Musica'), ('Servicios De Transmision', 'Servicios De Transmision'), ('Software De Idiomas', 'Software De Idiomas'), ('Salud Y Cuidado Personal', 'Salud Y Cuidado Personal'), ('Seguridad Informatica', 'Seguridad Informatica'), ('Traduccion De Idiomas', 'Traduccion De Idiomas'), ('Videollamadas', 'Videollamadas')], max_length=150, verbose_name='Tipo de software'),
        ),
    ]
