# Generated by Django 5.1.5 on 2025-02-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_created_at_alter_categorization_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorization',
            name='category',
            field=models.TextField(choices=[('Productividad', 'Productividad'), ('Creatividad', 'Creatividad'), ('Comunicación', 'Comunicacion'), ('Negocios', 'Negocios'), ('Programación', 'Programacion'), ('Entretenimiento', 'Entretenimiento'), ('Educativo', 'Educacion'), ('Bienestar y Salud', 'Bienestar Y Salud')], default='Productividad', max_length=255, verbose_name='Selecciona una categoría'),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='license',
            field=models.CharField(choices=[('Propietario', 'Propietario'), ('Libre', 'Libre'), ('Codigo Abierto', 'Codigo Abierto')], default='Propietario', max_length=50, verbose_name='¿Cuál es el Tipo de licencia?'),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='sector',
            field=models.CharField(choices=[('Estilo de Vida', 'Estilo De Vida'), ('Salud', 'Salud'), ('Educación', 'Educacion'), ('Finanzas y economia', 'Finanzas Y Economia'), ('Manufactura', 'Manufactura'), ('Transporte y logistica', 'Transporte Y Logistica'), ('Agricultura', 'Agricultura'), ('Gobierno', 'Gobierno'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Energía', 'Energia'), ('Recursos Humanos', 'Recursos Humanos'), ('Marketing', 'Marketing'), ('Legal', 'Legal'), ('Construcción', 'Construccion'), ('Turismo', 'Turismo'), ('Bienes Raíces', 'Bienes Raices'), ('Entretenimiento', 'Entretenimiento'), ('Deportes', 'Deportes'), ('Ciencia e investigación', 'Ciencia E Investigacion'), ('Servicios Publicos', 'Servicios Publicos'), ('Desarrollo de Software', 'Software'), ('Cuidado Animal', 'Cuidado Animal')], max_length=200, verbose_name='¿En qué sector se encuentra el desarrollo de software?'),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='software',
            field=models.CharField(choices=[('Software de Aplicación', 'Software De Aplicacion'), ('Software de Gestión', 'Software De Gestion'), ('Software de Programación', 'Software De Programacion'), ('Software de Sistema', 'Software De Sistema')], default='Software de Aplicación', max_length=150, verbose_name='¿Cuál es el Tipo de software, según sus funciones principales?'),
        ),
    ]
