# Generated by Django 5.1.5 on 2025-03-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_categorization_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='function_main',
            field=models.CharField(max_length=255, verbose_name='Funciones principales'),
        ),
    ]
