# Generated by Django 5.1.5 on 2025-03-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_project_function_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='goal_main',
            field=models.TextField(verbose_name='Objectivo principal'),
        ),
    ]
