# Generated by Django 5.1.5 on 2025-03-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_project_goal_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='goal_main',
            new_name='goal',
        ),
        migrations.RemoveField(
            model_name='project',
            name='function_main',
        ),
        migrations.RemoveField(
            model_name='project',
            name='public_goal',
        ),
    ]
