# Generated by Django 5.1.5 on 2025-03-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_rename_goal_main_project_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='version',
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
