# Generated by Django 5.1.5 on 2025-04-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_remove_project_version_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
