# Generated by Django 5.1.5 on 2025-04-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='goal',
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.TextField(default='kdlf', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
