# Generated by Django 5.1.5 on 2025-04-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_image_created_at_image_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-id',), 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
