# Generated by Django 5.1.5 on 2025-04-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_logo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
