# Generated by Django 5.1.5 on 2025-03-29 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0013_remove_project_version_alter_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('verse', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(choices=[('Aplicacion Web', 'Aplicacion Web'), ('Aplicacion Escritorio', 'Aplicacion Escritorio'), ('Aplicacion Movil', 'Aplicacion Movil'), ('Aplicacion IoT', 'Aplicacion Iot'), ('Mensajeria', 'Mensajeria'), ('Inteligencia Artificial', 'Inteligencia Artificial')], max_length=50)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
            },
        ),
    ]
