# Generated by Django 5.1.5 on 2025-03-29 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_remove_project_version_alter_project_title'),
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.CharField(choices=[('Aplicacion Web', 'Aplicacion Web'), ('Aplicacion Escritorio', 'Aplicacion Escritorio'), ('Aplicacion Movil', 'Aplicacion Movil'), ('Aplicacion IoT', 'Aplicacion Iot'), ('Mensajeria', 'Mensajeria'), ('Inteligencia Artificial', 'Inteligencia Artificial')], default='Aplicacion Web', max_length=50),
        ),
        migrations.AlterField(
            model_name='app',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='software', to='project.project'),
        ),
    ]
