# Generated by Django 5.1.5 on 2025-04-03 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_alter_app_category_alter_app_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Servidor de aplicaciones', 'Servidor De Aplicaciones'), ('Sistema gestor de base de datos', 'Sistema Gestor De Base De Datos'), ('Sistema operativo de despliegue', 'Sistema Operativo De Despliegue'), ('Navegador web', 'Navegador Web'), ('Motor de bases de datos', 'Motor De Base De Datos')], max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externals', to='software.externalsoftware')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Almacenamiento', 'Almacenamiento'), ('Memoria Ram', 'Memoria Ram'), ('Procesador', 'Procesador'), ('Pantalla', 'Pantalla'), ('Otro dispositivo', 'Otro Dispositivo')], max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to='software.app')),
            ],
            options={
                'verbose_name': 'Hardware',
                'verbose_name_plural': 'Hardwares',
            },
        ),
    ]
