# Generated by Django 5.1.5 on 2025-04-09 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_remove_participant_role_delete_role_participant_role'),
        ('software', '0003_externalsoftware_hardware'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('version', models.CharField(max_length=20)),
                ('fuente', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('importancia', models.CharField(choices=[('Vital', 'Vital')], max_length=50)),
                ('urgencia', models.CharField(choices=[('Inmediata', 'Inmediata')], max_length=50)),
                ('status', models.CharField(choices=[('Implementado', 'Implementado')], max_length=50)),
                ('estabilidad', models.CharField(choices=[('Alta', 'Alta')], max_length=50)),
                ('comments', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('authors', models.ManyToManyField(related_name='authors', to='author.participant')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetives', to='software.app')),
            ],
            options={
                'verbose_name': 'Objective',
                'verbose_name_plural': 'Objectives',
            },
        ),
    ]
