# Generated by Django 5.1.5 on 2025-04-11 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_remove_participant_role_delete_role_participant_role'),
        ('software', '0004_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='estabilidad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default=('Baja', 'Baja'), max_length=50),
        ),
        migrations.AlterField(
            model_name='objective',
            name='importancia',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default=('Baja', 'Baja'), max_length=50),
        ),
        migrations.AlterField(
            model_name='objective',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='software.app'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='status',
            field=models.CharField(choices=[('Implementado', 'Implementado'), ('Pendiente', 'Pendiente')], default=('Implementado', 'Implementado'), max_length=50),
        ),
        migrations.AlterField(
            model_name='objective',
            name='urgencia',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default=('Baja', 'Baja'), max_length=50),
        ),
        migrations.CreateModel(
            name='Requeriment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('version', models.CharField(max_length=20)),
                ('fuente', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('importancia', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default=('Baja', 'Baja'), max_length=50)),
                ('urgencia', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default=('Baja', 'Baja'), max_length=50)),
                ('status', models.CharField(choices=[('Implementado', 'Implementado'), ('Pendiente', 'Pendiente')], default=('Implementado', 'Implementado'), max_length=50)),
                ('estabilidad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default=('Baja', 'Baja'), max_length=50)),
                ('comments', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('authors', models.ManyToManyField(related_name='author', to='author.participant')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requeriments', to='software.app')),
            ],
            options={
                'verbose_name': 'Requeriment',
                'verbose_name_plural': 'Requeriments',
            },
        ),
    ]
