# Generated by Django 5.1.5 on 2025-04-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0005_alter_objective_estabilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requeriment',
            name='dependecy',
            field=models.CharField(default='2025-01-01', max_length=150),
            preserve_default=False,
        ),
    ]
