# Generated by Django 5.1.5 on 2025-04-12 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0006_requeriment_dependecy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requeriment',
            name='dependecy',
        ),
    ]
