# Generated by Django 5.1.5 on 2025-04-21 20:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0007_remove_requeriment_dependecy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='description', verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
