# Generated by Django 5.1.5 on 2025-04-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0010_alter_app_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='importancia',
            field=models.CharField(choices=[('Esencial', 'Esencial'), ('Prescindible', 'Prescindible')], default=('Esencial', 'Esencial'), max_length=50),
        ),
        migrations.AlterField(
            model_name='objective',
            name='urgencia',
            field=models.CharField(choices=[('Inmediata', 'Inmediata'), ('Puede esperar', 'Puede esperar')], default=('Inmediata', 'Inmediata'), max_length=50),
        ),
        migrations.AlterField(
            model_name='requeriment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requeriment',
            name='importancia',
            field=models.CharField(choices=[('Esencial', 'Esencial'), ('Prescindible', 'Prescindible')], default=('Esencial', 'Esencial'), max_length=50),
        ),
        migrations.AlterField(
            model_name='requeriment',
            name='urgencia',
            field=models.CharField(choices=[('Inmediata', 'Inmediata'), ('Puede esperar', 'Puede esperar')], default=('Inmediata', 'Inmediata'), max_length=50),
        ),
    ]
