# Generated by Django 5.1.5 on 2025-04-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0011_alter_objective_comments_alter_objective_importancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='objectiveId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
